### ISSUE TITLE
Reason for duplicating nodegraph?

### ISSUE THREAD

**Issue by ghost** [dchow1992/nemarkingmenu#12]
I was looking through the code and noticed 'markingmenunodegraph' is just a slightly edited version of Houdini's nodegraph.  When I replaced  markingmenunodegraph with nodegraph there was an issue with when Houdini's nodegraph was imported, which I was able to fix by wrapping the class definition for MarkingMenuMouseHandler and the import statement into a function.

I'm curious if this was the issue or if there was a different reason.

Thanks,
Tom

**Comment by dchow1992** [comment]
That indeed was the issue. I didnt know you could get around circular imports like that, thanks!
