### ISSUE TITLE
Sop Scatter V2 missing

### ISSUE THREAD

**Issue by MirHadi-jam** [dchow1992/nemarkingmenu#22]
Hello

thank you again for this fantastic tool. I use it everyday.
action scatter node in Sops only creates old scatter node not the new v2.

scatter 
scatter::2.0

thank you

**Comment by MirHadi-jam** [comment]
also remesh action created v1 

remesh 
remesh::2.0

**Comment by dchow1992** [comment]
Should be fixed now, sorry for taking forever to do this 
Release - v0.2.0
