### ISSUE TITLE
Copy to points v::2

### ISSUE THREAD

**Issue by MirHadi-jam** [dchow1992/nemarkingmenu#24]
Hello

Just Wow! 
I like your work. I love working with it. 
thank you for your effort and everything.

I think there might be others but I think with the latest version, there are still a few v::2 versions missing like:
- copytopoints  ( v::2 not created)
might you please fix this
thank you in advance

**Comment by dchow1992** [comment]
this should be fixed in the latest release, turned out the list of returned node types wasn't consistently ordered the same, so now we sort it ourselves. Hopefully this fixes the problem for the remaining nodes

**Comment by MirHadi-jam** [comment]
very very cool!
working perfectly
